### ISSUE TITLE
2 leds light up and that is it

### ISSUE THREAD

**Issue by ihavenofuckingclue** [RandomVertebrate/raspi-looper#14]
I am making this looper for a school project and whenever I power it only the GPIO 2 and GPIO 3 leds light up, and that's it. Nothing else functions. I have checked all hardware and software and it seems fine. The only difference that I have found is that I am using a raspberry pi 5 instead of 4b. Is there anything that would cause just 2 leds to light up within the raspberry pi?

**Comment by RandomVertebrate** [comment]
Hey, apologies for the delayed response. If you're still interested in the project perhaps you could post some output and I will see If I can figure anything out. I have never tried this on a Pi 5 personally, though, so I am not confident I will be able to help.

**Comment by ihavenofuckingclue** [comment]
No worries! I did fix it, just needed to mess around in rc.local a little. Instead of having the script change the directory then run main.py I just ran it direct by doing something like sudo python3 user/admin/raspi-looper/main.py.
