### ISSUE TITLE
Help with Jack connection

### ISSUE THREAD

**Issue by modante** [RandomVertebrate/raspi-looper#15]
Hello :-)
First of all, thank you very much for your project. It has inspired me to make some mods to your code in order to adapt it to my needs.

I have changed the 8 buttons (4 for play, 4 for rec) to 6:
-Rec
-Mute
-Undo
-Prev (change to the previous loop number)
-Next (change to the next loop number)
-Restart (changes mode from Looper to Fluidsynth
and I have added 10 audioloops instead of 4.

Also I only use 4 Led:
Leds on Rec Button: Yellow (red+green) when waiting and Red when recording
Leds on Mute Button: Yellow when waiting for UnMute and Green when Playing

I have implemented a is_waiting_play state in order to wait till readp == 0 to unmute the loop.

I share all my codes here because I don't know (I am a newby programmer) where I can share them.
[raspi-looper-mod.zip](https://github.com/user-attachments/files/17540497/raspi-looper-mod.zip)

The question is that I would like to adapt the code to run over jack instead of using PyAudio for two reasons:
- I would like to run simultaneously the looper and the fluidsynth
- I am using a Zoom H5 like USB audio interface and I need looper to capture the sum of the 4 mono audio inputs in order to use different instruments and mics connected to the physical inputs of the interface

I can see on this code that each block of 512 kb (buffer/chunk) it runs the looping_callback:
`looping_stream = pa.open(
    format = FORMAT,
    channels = CHANNELS,
    rate = RATE,
    input = True,
    output = True,
    input_device_index = INDEVICE,
    output_device_index = OUTDEVICE,
    frames_per_buffer = CHUNK,
    start = True,
    stream_callback = looping_callback
)`

Is there any easy way to adapt this code to Jack Client for Python? (https://jackclient-python.readthedocs.io/en/0.5.4/usage.html)

Thank you very much for your effort that is changing my setup like musician :-)

**Comment by modante** [comment]
![photo_2024-10-28_11-14-53](https://github.com/user-attachments/assets/53806e74-23ed-4780-989b-d6507a451ef0)
![photo_2024-10-28_11-15-12](https://github.com/user-attachments/assets/f793c97f-939c-4e97-89d0-97d878786fb3)

**Comment by RandomVertebrate** [comment]
Hey! Just saw this. Great to see your project!
From what I can see of the jack documentation it seems compatible. The code would need to be changed to fit with how jack works. As to where you can share your code, if you click "fork" while logged into github it will create a new copy of the repository that you own that you can make changes to etc. and it will help you keep track of changes.

**Comment by modante** [comment]
> Hey! Just saw this. Great to see your project! From what I can see of the jack documentation it seems compatible. The code would need to be changed to fit with how jack works. As to where you can share your code, if you click "fork" while logged into github it will create a new copy of the repository that you own that you can make changes to etc. and it will help you keep track of changes.

Hello :-D
I have created a new project because I am not sure how to do the fork when I have changed the code to adapt it to my hardware: https://github.com/modante/Raspi-Loop-Station
There is a "working" version of the adapted raspi-looper with pyAudio using 3 momentary buttons for Rec, Mute/Solo and Undo/Clear and 3 latched buttons (it is what I have at the moment, I will change them soon) for PrevLoop, NextLoop, and Mode (there is a Mode where FluidSynth runs an instance and PrevLoop and NextLoop Buttons changes the preset).
Then I have made a first version using Jack Client but still doesn't work: https://github.com/modante/Raspi-Loop-Station/tree/Jack-Implementation
I have a problem with buffers. I am not sure if the input buffer is been recorded on current_rec_buffer (line 540) or the play_buffer is been copied in the output_port.get_array() (line 616). The result is always silence.
Please, take a look at these lines. Maybe you get the trick at first sight.
Thank you very much :-)

**Comment by modante** [comment]
Hi :-)
Definitively I have solved the jack connection and added FluidSynth to the Looper.
I made a fork of your work and recently I uploaded all the files to the repository:
https://github.com/modante/LooPyStation

Thank you very much for your inspiring project :-D

**Comment by RandomVertebrate** [comment]
Awesome! I will definitely spend some time looking through your fork, it
always feels great to see people take something I did and get use out of it!
